### ISSUE TITLE
Exclusions List?

### ISSUE THREAD

**Issue by colinhemphill** [KanoComputing/nodejs-profanity-util#13]
Is there no way to exclude words from the default list? Some of them seem quite arbitrary. I run a profanity bot for a Slack team used by church staff and volunteers. The default list includes "God", "hell", etc, which obviously doesn't work for us. haha

I also don't care if people use "poop", "poo", "bum", etc. Those seem really arbitrary and extreme. Is there not a way to feed an array of words to exclude from the profanity check? I can do a PR and test this if it doesn't exist already.

**Comment by tancredi** [comment]
Hi @colinhemphill , you can feed `nodejs-profanity-util` with your own list of swearwords using the `forbiddenList` option ([see docs](https://github.com/KanoComputing/nodejs-profanity-util#api)) - I suggest forking off the default list from the repo and manually editing it for your codebase.

Hope this helps!
